import Header from '@/components/Header/Header';
import './globals.css';
import { Inter } from 'next/font/google';
import Footer from '@/components/Footer/Footer';
import AuthProvider from '@/Providers/AuthProvider';
import SafeRouteProvider from '@/Providers/SafeRouteProvider';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex flex-col max-h-screen min-h-screen justify-between flex-auto`}
      >
        <AuthProvider>
          <SafeRouteProvider>
            <main>{children}</main>
          </SafeRouteProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
